language: python
python:
  - '3.8.5'
install:
  - pip install -r requirements.txt
scripts:
  - python3 -m unittest discover -s './tests/unit' -p '*_test.py'
  - python3 -m unittest discover -s './tests/integration' -p '*_test.py'
